FROM node:20.12.2-bullseye-slim

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y dumb-init && \
    apt-get clean

WORKDIR /usr/src/app

ENTRYPOINT ["dumb-init"]

COPY ./package.json ./yarn.lock ./
RUN yarn

COPY . ./

EXPOSE 3000

CMD ["yarn", "dev"]
